version: '3.8'

services:
  postgress:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: entiti
      POSTGRES_PASSWORD: entiti
      POSTGRES_DB: class
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://entiti:entiti@localhost:5432/class?schema=public
    depends_on:
      - postgres

volumes:
  postgres_data:
